apiVersion: apps/v1
kind: Deployment
metadata:
  name: monorepo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monorepo-ui
  template:
    metadata:
      labels:
        app: monorepo-ui
    spec:
      containers:
        - name: monorepo-ui
          image: monorepo-ui:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
