apiVersion: v1
kind: Service
metadata:
  name: monorepo-ui
  namespace: private-heaven
spec:
  selector:
    app: monorepo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
