apiVersion: apps/v1
kind: Deployment
metadata:
  name: handbooks
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: handbooks
  template:
    metadata:
      labels:
        app: handbooks
    spec:
      containers:
        - name: handbooks
          image: ghcr.io/panicboat/monorepo/handbooks:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
