apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: develop

resources:
  - ../../base

images:
  - name: monorepo-ui
    newName: ghcr.io/panicboat/monorepo-ui
    newTag: develop
