apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: ghcr.io/panicboat/monoerepo/docs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
