apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reverse-proxy
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: nginx-config
  files:
  - nginx.conf=config/nginx.conf
  - upstream.conf=config/conf.d/upstream.conf
  - server.conf=config/conf.d/server.conf
  - docs.conf=config/conf.d/docs.conf
  - nyx.conf=config/conf.d/nyx.conf
