apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - httproute.yaml
  - service.yaml

configMapGenerator:
- name: nginx-main-config
  files:
  - nginx.conf=config/nginx.conf
- name: nginx-conf-d
  files:
  - config/conf.d/cilium-gateway.conf
  - config/conf.d/docs.conf
  - config/conf.d/nyx.conf
