---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reverse-proxy
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./reverse-proxy/kubernetes/overlays/develop"
  prune: true
  sourceRef:
    kind: GitRepository
    name: monorepo
  targetNamespace: default
  postBuild:
    substitute:
      service_name: reverse-proxy
