name: Reusable Container Builder

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: 'Name of the image (e.g. service-name)'
      working-directory:
        required: true
        type: string
        description: 'Directory containing the Dockerfile'
      app-id:
        required: true
        type: string
        description: 'GitHub App ID for authentication'
    secrets:
      private-key:
        required: true
        description: 'GitHub App private key for authentication'

jobs:
  build-and-push:
    if: inputs.image-name != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}
          owner: ${{ github.repository_owner }}

      - name: Build and push container with custom tags
        uses: panicboat/deploy-actions/container-builder@main
        with:
          # Use GITHUB_TOKEN to ensure permission to create new packages
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ inputs.image-name }}
          platforms: linux/arm64
          working-directory: ${{ inputs.working-directory }}
          tags-template: |
            type=raw,value=${{ github.actor}}
