apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app/deployment.yaml
  - app/httproute.yaml
  - app/service.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - app/index.html
    options:
      labels:
        app: nginx
labels:
  - pairs:
      app: nginx
